/**
 * CEKPay Mock Service Layer — Phase 4.2
 *
 * Every function:
 *   - Accepts typed parameters matching `src/types/index.ts`
 *   - Returns typed responses wrapped in `Promise<T>`
 *   - Uses `setTimeout` with 1500–3000 ms delay (simulates Nigerian network latency)
 *   - Transaction services have a 10% random failure rate (tests reversal UI)
 *
 * The in-memory `db` object is the single source of truth while the app is
 * running. On page refresh the data resets to the seed values from mockData.ts.
 *
 * @see Phase 4.2 in implementation_plan.md
 */

import type {
  User,
  Wallet,
  Transaction,
  Announcement,
  SmartContact,
  ProductPrice,
  AdminSettings,
  Promo,
  TransactionService,
  TransactionStatus,
  AnnouncementType,
  SignupRequest,
  AirtimeRequest,
  DataRequest,
  ElectricityRequest,
  CableRequest,
} from '../../types'

import {
  MOCK_USERS,
  MOCK_WALLETS,
  MOCK_TRANSACTIONS,
  MOCK_ANNOUNCEMENTS,
  MOCK_SMART_CONTACTS,
  ALL_PRODUCT_PRICES,
  MOCK_ADMIN_SETTINGS,
  MOCK_PROMOS,
} from './mockData'

import { generateAlphanumericPass } from './mockPassGenerator'

// ─── Configuration ────────────────────────────────────────

/** Simulated network latency range (ms). */
const MIN_DELAY = 1500
const MAX_DELAY = 3000

/** Probability a transaction service call "fails" (0.0 – 1.0). */
const FAILURE_RATE = 0.10

/** Maximum smart contacts per user (Director Decision #5). */
const MAX_SMART_CONTACTS = 10

// ─── In-Memory Database ───────────────────────────────────

/**
 * Mutable clone of all seed data. Functions mutate this directly.
 * Resets on page refresh (intentional for Phase 1 mock).
 */
const db = {
  users: [...MOCK_USERS] as User[],
  wallets: [...MOCK_WALLETS] as Wallet[],
  transactions: [...MOCK_TRANSACTIONS] as Transaction[],
  announcements: [...MOCK_ANNOUNCEMENTS] as Announcement[],
  smartContacts: [...MOCK_SMART_CONTACTS] as SmartContact[],
  productPrices: [...ALL_PRODUCT_PRICES] as ProductPrice[],
  adminSettings: { ...MOCK_ADMIN_SETTINGS } as AdminSettings,
  promos: [...MOCK_PROMOS] as Promo[],
  /** Stores the most-recently-generated pass per phone number. */
  pendingPasses: new Map<string, string>(),
}

// ─── Helpers ──────────────────────────────────────────────

/** Returns a random delay in [MIN_DELAY, MAX_DELAY]. */
function randomDelay(): number {
  return MIN_DELAY + Math.floor(Math.random() * (MAX_DELAY - MIN_DELAY + 1))
}

/** Wraps a value in a delayed Promise (simulates latency). */
function delayed<T>(value: T): Promise<T> {
  return new Promise((resolve) => setTimeout(() => resolve(value), randomDelay()))
}

/** Wraps an error in a delayed rejected Promise. */
function delayedError<T = never>(message: string): Promise<T> {
  return new Promise((_, reject) =>
    setTimeout(() => reject(new Error(message)), randomDelay()),
  )
}

/** Generates a unique-enough ID for new records. */
function uid(prefix: string): string {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`
}

/** Returns true ~FAILURE_RATE of the time. */
function shouldFail(): boolean {
  return Math.random() < FAILURE_RATE
}

/** Builds a transaction reference string. */
function txnRef(serviceCode: string): string {
  const now = new Date()
  const datePart = now.toISOString().slice(0, 10).replace(/-/g, '')
  const rand = Math.random().toString(36).slice(2, 6).toUpperCase()
  return `CEK-${serviceCode}-${datePart}-${rand}`
}

// ═══════════════════════════════════════════════════════════
//  AUTH SERVICES
// ═══════════════════════════════════════════════════════════

/**
 * Register a new user.
 * Returns the created User (without wallet — wallet is created in `mockCreatePin`).
 */
export async function mockSignup(data: SignupRequest): Promise<User> {
  // Check for duplicate phone
  const existing = db.users.find((u) => u.phone === data.phone)
  if (existing) {
    return delayedError('An account with this phone number already exists.')
  }

  const newUser: User = {
    id: uid('usr'),
    phone: data.phone,
    firstName: data.firstName,
    lastName: data.lastName,
    pinHash: '',          // Will be set in mockCreatePin
    role: 'user',
    isBanned: false,
  }

  db.users.push(newUser)
  return delayed(newUser)
}

/**
 * Generate and "send" a 6-char alphanumeric Pass.
 *
 * In production: BulkSMSNigeria delivers "Your CEKPay Pass is A7X9TP".
 * For mock: returns the pass directly so the dev can see it in console/UI.
 */
export async function mockSendPass(phone: string): Promise<{ pass: string }> {
  const pass = generateAlphanumericPass()
  db.pendingPasses.set(phone, pass)

  // Log for dev convenience
  console.info(`[CEKPay Mock] Pass for ${phone}: ${pass}`)

  return delayed({ pass })
}

/**
 * Validate the alphanumeric pass against the one generated by `mockSendPass`.
 */
export async function mockVerifyPass(phone: string, pass: string): Promise<boolean> {
  const stored = db.pendingPasses.get(phone)
  if (!stored) {
    return delayedError('No pass was sent to this number. Please request a new one.')
  }

  const isValid = stored.toUpperCase() === pass.toUpperCase()
  if (isValid) {
    db.pendingPasses.delete(phone) // One-time use
  }

  return delayed(isValid)
}

/**
 * Create the user's 4-digit PIN and provision their wallet.
 * Returns the wallet with DVA (Dedicated Virtual Account) details.
 */
export async function mockCreatePin(userId: string, pin: string): Promise<Wallet> {
  const user = db.users.find((u) => u.id === userId)
  if (!user) return delayedError('User not found.')

  if (pin.length !== 4 || !/^\d{4}$/.test(pin)) {
    return delayedError('PIN must be exactly 4 digits.')
  }

  // Store PIN (plaintext for mock; hashed in production)
  user.pinHash = pin

  // Provision wallet with DVA
  const wallet: Wallet = {
    id: uid('wal'),
    userId,
    balance: 0,
    paystackCustomerCode: `CUS_mock_${Math.random().toString(36).slice(2, 8)}`,
    accountNumber: user.phone.replace(/^0/, ''),   // Strip leading 0 for 10-digit DVA
    bankName: 'Wema Bank',
  }

  db.wallets.push(wallet)
  return delayed(wallet)
}

/**
 * Verify a user's 4-digit PIN.
 * Used by the App Lock screen AND transaction confirmation.
 */
export async function mockVerifyPin(userId: string, pin: string): Promise<boolean> {
  const user = db.users.find((u) => u.id === userId)
  if (!user) return delayedError('User not found.')

  return delayed(user.pinHash === pin)
}

/**
 * Log in an existing user by phone and PIN.
 * Returns the User object if successful.
 */
export async function mockLogin(phone: string, pin: string): Promise<User> {
  const user = db.users.find((u) => u.phone === phone)
  if (!user) {
    return delayedError('Invalid phone number or PIN.')
  }

  if (user.pinHash !== pin) {
    return delayedError('Invalid phone number or PIN.')
  }

  if (user.isBanned) {
    return delayedError('This account has been suspended. Please contact support.')
  }

  return delayed(user)
}

// ═══════════════════════════════════════════════════════════
//  DASHBOARD SERVICES
// ═══════════════════════════════════════════════════════════

/**
 * Fetch everything needed for the main dashboard in a single call.
 */
export async function mockGetDashboard(userId: string): Promise<{
  user: User
  wallet: Wallet
  announcements: Announcement[]
  smartContacts: SmartContact[]
}> {
  const user = db.users.find((u) => u.id === userId)
  if (!user) return delayedError('User not found.')

  const wallet = db.wallets.find((w) => w.userId === userId)
  if (!wallet) return delayedError('Wallet not found.')

  const announcements = db.announcements.filter((a) => a.isActive)
  const smartContacts = db.smartContacts.filter((sc) => sc.userId === userId)

  return delayed({ user, wallet, announcements, smartContacts })
}

// ═══════════════════════════════════════════════════════════
//  TRANSACTION SERVICES
// ═══════════════════════════════════════════════════════════

/**
 * Internal helper: debit the user's wallet and create a transaction record.
 * Applies the 10% random failure rate.
 */
async function processTransaction(
  userId: string,
  service: TransactionService,
  serviceCode: string,
  amount: number,
  extra: Partial<Transaction>,
): Promise<Transaction> {
  const wallet = db.wallets.find((w) => w.userId === userId)
  if (!wallet) return delayedError('Wallet not found.')

  if (wallet.balance < amount) {
    return delayedError(`Insufficient balance. You need ₦${amount.toLocaleString()} but have ₦${wallet.balance.toLocaleString()}.`)
  }

  // Determine outcome (10% failure rate)
  let status: TransactionStatus = 'Success'
  if (shouldFail()) {
    status = 'Failed'
  }

  // Only debit on success
  if (status === 'Success') {
    wallet.balance -= amount
  }

  const txn: Transaction = {
    id: uid('txn'),
    userId,
    reference: txnRef(serviceCode),
    type: 'Debit',
    service,
    amount,
    status,
    aggregatorUsed: Math.random() > 0.5 ? 'Toppa' : 'VTpass',
    createdAt: new Date().toISOString(),
    ...extra,
  }

  db.transactions.unshift(txn) // newest first

  return delayed(txn)
}

/**
 * Purchase airtime.
 */
export async function mockBuyAirtime(params: AirtimeRequest): Promise<Transaction> {
  // Find the calling user from any wallet (in real app, userId comes from auth)
  const wallet = db.wallets.find((w) => w.balance >= 0)
  const userId = wallet?.userId ?? 'usr_demo_001'

  return processTransaction(userId, 'Airtime', 'AIR', params.amount, {
    recipient: params.phone,
    provider: params.network,
    planName: `₦${params.amount.toLocaleString()} Airtime`,
  })
}

/**
 * Purchase a data bundle.
 */
export async function mockBuyData(params: DataRequest): Promise<Transaction> {
  const plan = db.productPrices.find((p) => p.id === params.planId)
  if (!plan) return delayedError('Data plan not found.')
  if (!plan.isActive) return delayedError('This data plan is currently unavailable.')

  const wallet = db.wallets.find((w) => w.balance >= 0)
  const userId = wallet?.userId ?? 'usr_demo_001'

  return processTransaction(userId, 'Data', 'DAT', plan.retailPrice, {
    recipient: params.phone,
    provider: params.network,
    planName: plan.planName,
  })
}

/**
 * Pay for prepaid electricity token.
 */
export async function mockPayElectricity(params: ElectricityRequest): Promise<Transaction> {
  const wallet = db.wallets.find((w) => w.balance >= 0)
  const userId = wallet?.userId ?? 'usr_demo_001'

  return processTransaction(userId, 'Electricity', 'ELE', params.amount, {
    recipient: params.meterNumber,
    provider: params.disco,
  })
}

/**
 * Pay for cable TV subscription.
 */
export async function mockPayCable(params: CableRequest): Promise<Transaction> {
  const plan = db.productPrices.find((p) => p.id === params.planId)
  if (!plan) return delayedError('Cable plan not found.')
  if (!plan.isActive) return delayedError('This cable plan is currently unavailable.')

  const wallet = db.wallets.find((w) => w.balance >= 0)
  const userId = wallet?.userId ?? 'usr_demo_001'

  return processTransaction(userId, 'Cable', 'CAB', plan.retailPrice, {
    recipient: params.iucNumber,
    provider: params.provider,
    planName: plan.planName,
  })
}

/**
 * Fetch transaction history for a user, sorted newest-first.
 */
export async function mockGetTransactions(userId: string): Promise<Transaction[]> {
  const userTxns = db.transactions.filter((t) => t.userId === userId)
  return delayed(userTxns)
}

/**
 * Fetch product prices filtered by service type.
 * Returns only active products.
 */
export async function mockGetProductPrices(service: TransactionService): Promise<ProductPrice[]> {
  const prices = db.productPrices.filter(
    (p) => p.service === service && p.isActive,
  )
  return delayed(prices)
}

// ═══════════════════════════════════════════════════════════
//  SMART CONTACTS SERVICES
// ═══════════════════════════════════════════════════════════

/**
 * Add a new smart contact for the user.
 * Rejects if the user already has MAX_SMART_CONTACTS (Director Decision #5: max 10).
 */
export async function mockAddSmartContact(
  contact: Omit<SmartContact, 'id'>,
): Promise<SmartContact> {
  const userContacts = db.smartContacts.filter((sc) => sc.userId === contact.userId)
  if (userContacts.length >= MAX_SMART_CONTACTS) {
    return delayedError(
      `You can save a maximum of ${MAX_SMART_CONTACTS} smart contacts. Please delete one to add a new one.`,
    )
  }

  const newContact: SmartContact = {
    id: uid('sc'),
    ...contact,
  }

  db.smartContacts.push(newContact)
  return delayed(newContact)
}

/**
 * Delete a smart contact by ID.
 */
export async function mockDeleteSmartContact(contactId: string): Promise<void> {
  const index = db.smartContacts.findIndex((sc) => sc.id === contactId)
  if (index === -1) return delayedError('Contact not found.')

  db.smartContacts.splice(index, 1)
  return delayed(undefined)
}

/**
 * Update fields on an existing smart contact.
 */
export async function mockUpdateSmartContact(
  contactId: string,
  updates: Partial<SmartContact>,
): Promise<SmartContact> {
  const contact = db.smartContacts.find((sc) => sc.id === contactId)
  if (!contact) return delayedError('Contact not found.')

  Object.assign(contact, updates)
  return delayed(contact)
}

// ═══════════════════════════════════════════════════════════
//  ADMIN SERVICES
// ═══════════════════════════════════════════════════════════

/**
 * Toggle aggregator API settings (primary/secondary).
 */
export async function mockAdminToggleAggregator(
  setting: string,
  value: string,
): Promise<void> {
  const validSettings = ['primaryDataApi', 'secondaryDataApi', 'primaryBillsApi'] as const
  const validValues = ['Toppa', 'VTpass'] as const

  if (!validSettings.includes(setting as typeof validSettings[number])) {
    return delayedError(`Invalid setting: ${setting}`)
  }
  if (!validValues.includes(value as typeof validValues[number])) {
    return delayedError(`Invalid aggregator: ${value}. Must be 'Toppa' or 'VTpass'.`)
  }

  const key = setting as keyof Pick<AdminSettings, 'primaryDataApi' | 'secondaryDataApi' | 'primaryBillsApi'>
  db.adminSettings[key] = value as AdminSettings[typeof key]
  return delayed(undefined)
}

/**
 * Create a new announcement.
 */
export async function mockAdminCreateAnnouncement(
  message: string,
  type: AnnouncementType,
): Promise<Announcement> {
  const announcement: Announcement = {
    id: uid('ann'),
    message,
    isActive: true,
    type,
  }

  db.announcements.push(announcement)
  return delayed(announcement)
}

/**
 * Fund a user's wallet (admin credit).
 */
export async function mockAdminFundWallet(
  userId: string,
  amount: number,
): Promise<void> {
  const wallet = db.wallets.find((w) => w.userId === userId)
  if (!wallet) return delayedError('Wallet not found for this user.')

  if (amount <= 0) return delayedError('Amount must be greater than zero.')

  wallet.balance += amount

  // Record the funding transaction
  const txn: Transaction = {
    id: uid('txn'),
    userId,
    reference: txnRef('ADM-FND'),
    type: 'Credit',
    service: 'Funding',
    amount,
    status: 'Success',
    createdAt: new Date().toISOString(),
  }
  db.transactions.unshift(txn)

  return delayed(undefined)
}

/**
 * Debit a user's wallet (admin debit with reason).
 */
export async function mockAdminDebitWallet(
  userId: string,
  amount: number,
  reason: string,
): Promise<void> {
  const wallet = db.wallets.find((w) => w.userId === userId)
  if (!wallet) return delayedError('Wallet not found for this user.')

  if (amount <= 0) return delayedError('Amount must be greater than zero.')
  if (wallet.balance < amount) {
    return delayedError(
      `Cannot debit ₦${amount.toLocaleString()}. User balance is ₦${wallet.balance.toLocaleString()}.`,
    )
  }

  wallet.balance -= amount

  // Record the debit transaction with reason in planName for audit trail
  const txn: Transaction = {
    id: uid('txn'),
    userId,
    reference: txnRef('ADM-DEB'),
    type: 'Debit',
    service: 'Funding',
    amount,
    status: 'Success',
    createdAt: new Date().toISOString(),
    planName: `Admin debit: ${reason}`,
  }
  db.transactions.unshift(txn)

  return delayed(undefined)
}

/**
 * Ban a user account.
 */
export async function mockAdminBanUser(userId: string): Promise<void> {
  const user = db.users.find((u) => u.id === userId)
  if (!user) return delayedError('User not found.')

  if (user.role === 'admin') {
    return delayedError('Cannot ban an admin account.')
  }

  user.isBanned = true
  return delayed(undefined)
}

/**
 * Fetch Admin Dashboard statistics.
 */
export async function mockAdminGetDashboard() {
  const usersCount = db.users.length
  const transactionsCount = db.transactions.length
  
  // Calculate revenue for today
  const today = new Date().toISOString().slice(0, 10)
  const revenueToday = db.transactions
    .filter(t => t.status === 'Success' && t.createdAt.startsWith(today))
    .reduce((sum, t) => sum + t.amount, 0)
    
  const activeAnnouncementsCount = db.announcements.filter(a => a.isActive).length
  
  // Get recent 20 transactions
  const recentTransactions = [...db.transactions]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 20)

  return delayed({
    usersCount,
    transactionsCount,
    revenueToday,
    activeAnnouncementsCount,
    recentTransactions
  })
}

export type AdminUserView = User & {
  balance: number
  joinedDate: string
}

/**
 * Fetch all users with their wallet balances for Admin view.
 */
export async function mockAdminGetUsers(): Promise<AdminUserView[]> {
  const usersWithWallets = db.users.map(user => {
    const wallet = db.wallets.find(w => w.userId === user.id)
    return {
      ...user,
      balance: wallet ? wallet.balance : 0,
      joinedDate: new Date(Date.now() - Math.random() * 10000000000).toISOString() // Mock join date
    }
  })
  return delayed(usersWithWallets)
}

/**
 * Unban a user account.
 */
export async function mockAdminUnbanUser(userId: string): Promise<void> {
  const user = db.users.find((u) => u.id === userId)
  if (!user) return delayedError('User not found.')

  user.isBanned = false
  return delayed(undefined)
}

// ═══════════════════════════════════════════════════════════
//  ADMIN SETTINGS & PROMOS (Bonus Read Accessors)
// ═══════════════════════════════════════════════════════════

/**
 * Fetch current admin settings.
 */
export async function mockAdminGetSettings(): Promise<AdminSettings> {
  return delayed({ ...db.adminSettings })
}

/**
 * Toggle maintenance mode.
 */
export async function mockAdminToggleMaintenance(enabled: boolean): Promise<void> {
  db.adminSettings.maintenanceMode = enabled
  return delayed(undefined)
}

/**
 * Fetch all announcements (active and inactive).
 */
export async function mockAdminGetAnnouncements(): Promise<Announcement[]> {
  return delayed([...db.announcements])
}

/**
 * Toggle an announcement's active state.
 */
export async function mockAdminToggleAnnouncement(
  announcementId: string,
  isActive: boolean,
): Promise<void> {
  const ann = db.announcements.find((a) => a.id === announcementId)
  if (!ann) return delayedError('Announcement not found.')

  ann.isActive = isActive
  return delayed(undefined)
}

/**
 * Fetch all promos.
 */
export async function mockAdminGetPromos(): Promise<Promo[]> {
  return delayed([...db.promos])
}

/**
 * Toggle a promo's active state.
 */
export async function mockAdminTogglePromo(promoId: string, isActive: boolean): Promise<void> {
  const promo = db.promos.find((p) => p.id === promoId)
  if (!promo) return delayedError('Promo not found.')

  promo.isActive = isActive
  return delayed(undefined)
}

/**
 * Create a new promo.
 */
export async function mockAdminCreatePromo(data: Omit<Promo, 'id' | 'isActive'>): Promise<Promo> {
  const promo: Promo = {
    ...data,
    id: uid('prm'),
    isActive: true,
  }
  db.promos.push(promo)
  return delayed(promo)
}

/**
 * Fetch all product prices (admin view — includes inactive).
 */
export async function mockAdminGetProductPrices(): Promise<ProductPrice[]> {
  return delayed([...db.productPrices])
}

/**
 * Toggle a product's active state.
 */
export async function mockAdminToggleProduct(
  priceId: string,
  isActive: boolean,
): Promise<void> {
  const price = db.productPrices.find((p) => p.id === priceId)
  if (!price) return delayedError('Product not found.')

  price.isActive = isActive
  return delayed(undefined)
}

/**
 * Update pricing for multiple products.
 */
export async function mockAdminUpdatePricing(updates: { id: string, retailPrice: number }[]): Promise<void> {
  for (const update of updates) {
    const price = db.productPrices.find(p => p.id === update.id)
    if (price && update.retailPrice > 0) {
      price.retailPrice = update.retailPrice
    }
  }
  return delayed(undefined)
}

// ═══════════════════════════════════════════════════════════
//  DATABASE ACCESS (for stores that need direct reads)
// ═══════════════════════════════════════════════════════════

/**
 * Exposes the in-memory DB for read access by Zustand stores.
 * This avoids duplicating data across multiple modules.
 *
 * IMPORTANT: Do not mutate the returned objects directly from
 * outside this module — always go through service functions.
 */
export function getMockDb() {
  return db
}
